[project]
name = "dilemma-scraper"
version = "1.1.0dev1"
description = "Simple web scraper to retreive ACP Doctor's Dilemma jeopardy questions from posted examples."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "loguru>=0.7.3",
    "playwright>=1.63.0",
    "polars>=1.44.2",
]